# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
export HADOOP_HOME=/home/deepmap/hadoop
export HADOOP_HDFS_HOME=/home/deepmap/hadoop
export PATH=$HADOOP_HOME/bin:$PATH

export LANG=en_US.UTF-8
export PYTHONPATH="/home/deepmap/xgboost/python-package:/home/deepmap/mxnet/python:/home/deepmap/mxnet/example/image-classification:${PYTHONPATH}"

alias la='ls -a'
alias vi='vim'
alias v='ls -l'
alias s='source ~/.bashrc'
alias vb='vi ~/.bashrc'
alias grep='grep --color'
alias e='exit'
alias pscp='pscp.pssh'

