# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -lF'
alias la='ls -A'
alias l='ls -CF'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

#export LANG=zh_CN.utf8
export PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot: +($debian_chroot)}\u@\h:\W\$ '

export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

#export HADOOP_HOME=~/disk2/hadoop/hadoop-0.20.2
#export BTRACE_HOME=~/disk2/soft/btrace-1.1.3
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
export M2_HOME="/Users/didi/soft/apache-maven-3.3.9"
export GRADLE_HOME="/Users/didi/soft/gradle-2.13"
export SCALA_HOME="/Users/didi/soft/scala-2.11.8"
export CLASSPATH=".:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar"
export ANT_HOME="/Users/didi/soft/apache-ant-1.9.7"
export BISON_HOME="/usr/local/Cellar/bison/3.0.4"
export PATH="$GRADLE_HOME/bin:$BISON_HOME/bin:$SCALA_HOME/bin:$BTRACE_HOME/bin:$M2_HOME/bin:$ANT_HOME/bin:$JAVA_HOME/bin:/usr/bin:/usr/local/bin:$PATH"

export MAVEN_OPTS="-Xmx4096m -XX:MaxPermSize=1024m"

alias la='ls -a'
alias vi='vim'
alias v='ls -l'
alias s='source ~/.bash_profile'
alias grep='grep --color'
alias vb='vi ~/.bash_profile'
alias e='exit'

yjp_home="~/disk2/soft/yjp-12.0.5"
alias yjp="nohup ${yjp_home}/bin/yjp.sh 1>/tmp/yjp.log 2>&1 </dev/null &"
alias vhost='ssh guili.ll@10.125.4.190' 

#alias outlink='ssh -D 26000 luoli@106.187.49.135'
alias outlink='ssh -D 26000 luoli@192.81.130.37'
alias cddisk2='cd ~/disk2'
alias cdsoft='cd ~/soft'
alias cddoc='cd ~/Documents'
alias cdhadoop='cd ~/disk2/hadoop'
alias cdsvn='cd ~/dev/svn' 
alias cdgit='cd ~/dev/git' 
alias cdtrunk='cd ~/dev/svn/Road2Cloud/trunk/hadoop-core' 
alias cdbranches='cd ~/dev/svn/Road2Cloud/branches' 
alias cdha='cd ~/dev/svn/Road2Cloud/branches/yunti-branch-for-NN-HA' 
alias cdcloud='cd ~/dev/svn/Road2Cloud/'
alias cdfede='cd ~/dev/svn/Road2Cloud/branches/hdfs-branch-for-federation' 
alias cdhdfs='cd ~/dev/svn/Road2Cloud/yunti-hdfs'
alias cdcommon='cd ~/dev/svn/Road2Cloud/yunti-common' 
alias cdmr='cd ~/dev/svn/Road2Cloud/yunti-mr' 
alias otrunk='cd ~/dev/svn/Apsara/odps/trunk' 

#alias unix2dos='todos' 
#alias dos2unix='fromdos'

alias hls='bin/hadoop fs -ls '
alias hlsr='bin/hadoop fs -lsr '
alias hrm='bin/hadoop fs -rm '
alias hrmr='bin/hadoop fs -rmr '
alias hget='bin/hadoop fs -get '
alias hput='bin/hadoop fs -put '
alias htouchz='bin/hadoop fs -touchz '
alias hdu='bin/hadoop fs -du '
alias hdus='bin/hadoop fs -dus '
alias hcount='bin/hadoop fs -count '
alias hmv='bin/hadoop fs -mv '
alias hcat='bin/hadoop fs -cat '
alias htext='bin/hadoop fs -text '
alias hmkdir='bin/hadoop fs -mkdir '

alias p='ibus-daemon -drx'

PATH=$PATH:$HOME/dev/soft/scala-2.10.3/bin:$HOME/.rvm/bin # Add RVM to PATH for scripting

#for mac shell color
#export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;36m\]\w\[\033[00m\]\$ '

#enables colorin the terminal bash shell export

export CLICOLOR=1
#sets up thecolor scheme for list export
LSCOLORS=gxfxcxdxbxegedabagacad

#sets up theprompt color (currently a green similar to linux terminal)
#export PS1='\u@\h:\w\$ '
export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;36m\]\w\[\033[00m\]\$ '

#enables colorfor iTerm
#export TERM=linux


#github
alias gst='git status '
alias gbranch='git branch '
alias gcheckout='git checkout '
alias gpull='git pull '
alias gpush='git push '
alias gremote='git remote '
alias gadd='git add '
alias gcommit='git commit '
alias gfetch='git fetch '


#zhoushuanghui
alias tozshnn='ssh 120.55.74.90 -l root'


#alluxio
alias acleanbuild='mvn -T 2C clean install -DskipTests -Dmaven.javadoc.skip -Dfindbugs.skip -Dcheckstyle.skip -Pdeveloper -Dhadoop.version=2.6.0 '
alias abuild='mvn -T 2C install -DskipTests -Dmaven.javadoc.skip -Dfindbugs.skip -Dcheckstyle.skip -Pdeveloper -Dhadoop.version=2.6.0 '
alias aeclipse='mvn clean -Pdeveloper -DskipTests eclipse:eclipse -DdownloadJavadocs=true -DdownloadSources=true '


# spark
alias scleanbuild="build/mvn -Pyarn -Phadoop-2.6 -Dhadoop.version=2.6.0 -DskipTests -Phive -Phive-thriftserver -Dmaven.javadoc.skip -Dfindbugs.skip -Dcheckstyle.skip clean install "
alias sbuild="build/mvn -Pyarn -Phadoop-2.6 -Dhadoop.version=2.6.0 -DskipTests -Phive -Phive-thriftserver -Dmaven.javadoc.skip -Dfindbugs.skip -Dcheckstyle.skip install "

# flink
alias fcleanbuild="mvn clean install -DskipTests -Dhadoop.version=2.6.1"
alias fbuild="mvn install -DskipTests -Dhadoop.version=2.6.1"


# didi tiaobanji
alias xg="ssh 10.93.44.28 -l luolinofear"
